//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis.Xaml {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XamlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XamlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeAnalysis.Xaml.XamlResources", typeof(XamlResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t reference compilation of type &apos;{0}&apos; from {1} compilation..
        /// </summary>
        internal static string CantReferenceCompilationOf {
            get {
                return ResourceManager.GetString("CantReferenceCompilationOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaining speculative semantic model is not supported. You should create a speculative model from the non-speculative ParentModel..
        /// </summary>
        internal static string ChainingSpeculativeModelIsNotSupported {
            get {
                return ResourceManager.GetString("ChainingSpeculativeModelIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation (C#): .
        /// </summary>
        internal static string CompilationC {
            get {
                return ResourceManager.GetString("CompilationC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file..
        /// </summary>
        internal static string CouldNotFindFile {
            get {
                return ResourceManager.GetString("CouldNotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements cannot be null..
        /// </summary>
        internal static string ElementsCannotBeNull {
            get {
                return ResourceManager.GetString("ElementsCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overloaded method &apos;{0}&apos; cannot be used in a compiled binding..
        /// </summary>
        internal static string Error_AmbiguousBindMethod {
            get {
                return ResourceManager.GetString("Error_AmbiguousBindMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous type reference. A type named &apos;{0}&apos; occurs in at least two namespaces, &apos;{1}&apos; and &apos;{2}&apos;. Consider adjusting the assembly XmlnsDefinition attributes..
        /// </summary>
        internal static string Error_AmbiguousTypeReference {
            get {
                return ResourceManager.GetString("Error_AmbiguousTypeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; was not found. Verify that you are not missing an assembly reference. Also, verify that your project and all referenced assemblies have been built..
        /// </summary>
        internal static string Error_AssemblyNotPartOfProject {
            get {
                return ResourceManager.GetString("Error_AssemblyNotPartOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Choice element must be included in an AlternateContent element..
        /// </summary>
        internal static string Error_AtLeastOneChoiceMustBePresent {
            get {
                return ResourceManager.GetString("Error_AtLeastOneChoiceMustBePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; is set more than one time..
        /// </summary>
        internal static string Error_AttributeAlreadyDefined {
            get {
                return ResourceManager.GetString("Error_AttributeAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeConverter syntax error encountered while processing initialization string &apos;{0}&apos;. Element attributes are not allowed on objects created via TypeConverter..
        /// </summary>
        internal static string Error_AttributesNotSupportedWithConverters {
            get {
                return ResourceManager.GetString("Error_AttributesNotSupportedWithConverters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain a value for the attribute &apos;{0}&apos;..
        /// </summary>
        internal static string Error_AttributeValueNotSupported {
            get {
                return ResourceManager.GetString("Error_AttributeValueNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in decimal character entity. Decimal character entities must only contain digits between &apos;0&apos; and &apos;9&apos;..
        /// </summary>
        internal static string Error_BadDecimalDigit {
            get {
                return ResourceManager.GetString("Error_BadDecimalDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in hexadecimal character entity. Hexadecimal character entities must contain digits between &apos;0&apos; and &apos;9&apos;, or letters between &apos;a&apos; and &apos;f&apos; or &apos;A&apos; and &apos;F&apos;..
        /// </summary>
        internal static string Error_BadHexDigit {
            get {
                return ResourceManager.GetString("Error_BadHexDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires a method with a single parameter of type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_BindBackError {
            get {
                return ResourceManager.GetString("Error_BindBackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To generate an event handler the class &apos;{0}&apos;, specified by the x:Class or x:Subclass attribute, must be the first class in the file. Move the class code so that it is the first class in the file and try again..
        /// </summary>
        internal static string Error_BindingClassNotFirst {
            get {
                return ResourceManager.GetString("Error_BindingClassNotFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one of includedPatterns or excludedPatterns can be non-null.
        /// </summary>
        internal static string Error_BothIncludeExcludeNonNull {
            get {
                return ResourceManager.GetString("Error_BothIncludeExcludeNonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource for URI{0} could not be loaded..
        /// </summary>
        internal static string Error_CannotLoadUri {
            get {
                return ResourceManager.GetString("Error_CannotLoadUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot mix private and public mergable messages..
        /// </summary>
        internal static string Error_CannotMixMessageTypes {
            get {
                return ResourceManager.GetString("Error_CannotMixMessageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting a cast with an attached property is not supported..
        /// </summary>
        internal static string Error_CastCannotStarWithAttachedProperty {
            get {
                return ResourceManager.GetString("Error_CastCannotStarWithAttachedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing tag for element &apos;&lt;{0}&gt;&apos; was not found..
        /// </summary>
        internal static string Error_ClosingTagMismatch {
            get {
                return ResourceManager.GetString("Error_ClosingTagMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value of type &apos;{1}&apos; cannot be added to a collection or dictionary of type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CollectionElementTypeMismatch {
            get {
                return ResourceManager.GetString("Error_CollectionElementTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment was terminated incorrectly. Comments are terminated with the characters &apos;--&gt;&apos;, not &apos;--!&gt;&apos;..
        /// </summary>
        internal static string Error_CommentedEndedWithDoubleHyphenBangGreaterThan {
            get {
                return ResourceManager.GetString("Error_CommentedEndedWithDoubleHyphenBangGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments cannot contain two adjacent hyphens &apos;--&apos;. Two adjacent hyphens &apos;--&apos; must be followed by a close angle bracket character &apos;&gt;&apos; to terminate the comment..
        /// </summary>
        internal static string Error_CommentWithDoubleHyphen {
            get {
                return ResourceManager.GetString("Error_CommentWithDoubleHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while committing changes to the designer.  You should immediately close the designer and re-open it.  Before saving changes, examine the markup in the XAML tab to ensure it is not corrupt.  The error was &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CommitFailed {
            get {
                return ResourceManager.GetString("Error_CommitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Commit method on SourceModifier has not been called..
        /// </summary>
        internal static string Error_CommitNotCalled {
            get {
                return ResourceManager.GetString("Error_CommitNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source modifier has already been committed and cannot be modified further..
        /// </summary>
        internal static string Error_CommittedModifier {
            get {
                return ResourceManager.GetString("Error_CommittedModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not support direct content..
        /// </summary>
        internal static string Error_ContentNotSupported {
            get {
                return ResourceManager.GetString("Error_ContentNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The designer context for {0} is currently detaching from the project and cannot be retrieved..
        /// </summary>
        internal static string Error_ContextDetaching {
            get {
                return ResourceManager.GetString("Error_ContextDetaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyDescriptor for &apos;{0}&apos; in type &apos;{1}&apos; was not found..
        /// </summary>
        internal static string Error_DescriptorNotFound {
            get {
                return ResourceManager.GetString("Error_DescriptorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The designer has already been loaded..
        /// </summary>
        internal static string Error_DesignerAlreadyLoaded {
            get {
                return ResourceManager.GetString("Error_DesignerAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The designer has not been loaded yet..
        /// </summary>
        internal static string Error_DesignerNotLoaded {
            get {
                return ResourceManager.GetString("Error_DesignerNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document has not been loaded into the document manager..
        /// </summary>
        internal static string Error_DocumentManagerNotLoaded {
            get {
                return ResourceManager.GetString("Error_DocumentManagerNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; does not appear to be a text document.  Only text documents can be edited..
        /// </summary>
        internal static string Error_DocumentNotTextStream {
            get {
                return ResourceManager.GetString("Error_DocumentNotTextStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Done method must be called on a source changer before passing it to this API..
        /// </summary>
        internal static string Error_DoneNotCalled {
            get {
                return ResourceManager.GetString("Error_DoneNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML document must contain a root level element..
        /// </summary>
        internal static string Error_EmptyDocument {
            get {
                return ResourceManager.GetString("Error_EmptyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A namespace prefix declaration cannot be empty..
        /// </summary>
        internal static string Error_EmptyXmlnsDeclaration {
            get {
                return ResourceManager.GetString("Error_EmptyXmlnsDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text cannot be copied in the document because the ending location of &apos;{0}&apos; is before the current cursor position of &apos;{1}&apos;..
        /// </summary>
        internal static string Error_EndingBeforeCursor {
            get {
                return ResourceManager.GetString("Error_EndingBeforeCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric entity is out of range. The value specified is not a valid Unicode value. Valid ranges: #x20-#xD7FF, #xE000-#xFFFD, #x10000-#x10FFFF and #x9, #xA, #xD..
        /// </summary>
        internal static string Error_EntityOverflow {
            get {
                return ResourceManager.GetString("Error_EntityOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not a collection..
        /// </summary>
        internal static string Error_ExpectedCollection {
            get {
                return ResourceManager.GetString("Error_ExpectedCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;{0}&apos;..
        /// </summary>
        internal static string Error_ExpectedDifferentToken {
            get {
                return ResourceManager.GetString("Error_ExpectedDifferentToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier expected. Expected a valid XAML name..
        /// </summary>
        internal static string Error_ExpectedIdentifier {
            get {
                return ResourceManager.GetString("Error_ExpectedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;{0}&apos; on type &apos;{1}&apos; to be an instance member..
        /// </summary>
        internal static string Error_ExpectedInstanceMember {
            get {
                return ResourceManager.GetString("Error_ExpectedInstanceMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a method..
        /// </summary>
        internal static string Error_ExpectedMethod {
            get {
                return ResourceManager.GetString("Error_ExpectedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; does not have a value..
        /// </summary>
        internal static string Error_ExpectedPropertyValue {
            get {
                return ResourceManager.GetString("Error_ExpectedPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;{0}&apos; on type &apos;{1}&apos; to be a static..
        /// </summary>
        internal static string Error_ExpectedStatic {
            get {
                return ResourceManager.GetString("Error_ExpectedStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an attribute value. Attribute values are delimited by a single quotation mark (&apos;) or a double quotation mark (&quot;)..
        /// </summary>
        internal static string Error_ExpectedString {
            get {
                return ResourceManager.GetString("Error_ExpectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an unexpected token causing the XML to be invalid. White space is expected..
        /// </summary>
        internal static string Error_ExpectedWhitespace {
            get {
                return ResourceManager.GetString("Error_ExpectedWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Choice element cannot follow a Fallback element in an AlternateContent element. Move the Fallback element to be last..
        /// </summary>
        internal static string Error_FallbackMustBeLast {
            get {
                return ResourceManager.GetString("Error_FallbackMustBeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using a converter with function binding is not supported..
        /// </summary>
        internal static string Error_FunctionBindWithConverter {
            get {
                return ResourceManager.GetString("Error_FunctionBindWithConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a function overload that takes {0} parameters..
        /// </summary>
        internal static string Error_FunctionParameterCountMismatched {
            get {
                return ResourceManager.GetString("Error_FunctionParameterCountMismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editor view cannot be displayed..
        /// </summary>
        internal static string Error_GenericEditorError {
            get {
                return ResourceManager.GetString("Error_GenericEditorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot navigate to definition..
        /// </summary>
        internal static string Error_GotoDefinitionFailed {
            get {
                return ResourceManager.GetString("Error_GotoDefinitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description for type &apos;{0}&apos; not found in the XAML language service host..
        /// </summary>
        internal static string Error_HostTypeNameNotFound {
            get {
                return ResourceManager.GetString("Error_HostTypeNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid white space. White space cannot follow the open angle bracket character &apos;&lt;&apos; in an element tag..
        /// </summary>
        internal static string Error_IllegalWhitespaceInIdentifier {
            get {
                return ResourceManager.GetString("Error_IllegalWhitespaceInIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; cannot be opened because it is already opened in another editor.  Close other document windows that are using this file and try again..
        /// </summary>
        internal static string Error_IncompatibleOpenEditor {
            get {
                return ResourceManager.GetString("Error_IncompatibleOpenEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No constructor for type &apos;{0}&apos; has {1} parameters..
        /// </summary>
        internal static string Error_IncorrectNumberOfCtorArguments {
            get {
                return ResourceManager.GetString("Error_IncorrectNumberOfCtorArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AsyncResult..
        /// </summary>
        internal static string Error_InvalidAsyncResult {
            get {
                return ResourceManager.GetString("Error_InvalidAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source changer passed to this API must be one that was created by &apos;{0}&apos;..
        /// </summary>
        internal static string Error_InvalidChanger {
            get {
                return ResourceManager.GetString("Error_InvalidChanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value of type &apos;{1}&apos; cannot be added a child of type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_InvalidChildType {
            get {
                return ResourceManager.GetString("Error_InvalidChildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mapping URI syntax. Must take the form &apos;clr-namespace:&lt;clr namespace&gt;[;assembly=&lt;assembly name&gt;]&apos;..
        /// </summary>
        internal static string Error_InvalidClrNamespaceSyntax {
            get {
                return ResourceManager.GetString("Error_InvalidClrNamespaceSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event &apos;{0}&apos; can only be bound to properties of delegate type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_InvalidEventBinding {
            get {
                return ResourceManager.GetString("Error_InvalidEventBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .guides file can&apos;t be opened and may be corrupted.  The existing file will be replaced with a new .guides file..
        /// </summary>
        internal static string Error_InvalidGuidesMessage {
            get {
                return ResourceManager.GetString("Error_InvalidGuidesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Ignorable attribute value. Ignorable must contain a space delimited list of prefixes defined by xmlns declarations in scope..
        /// </summary>
        internal static string Error_InvalidIgnorableAttribute {
            get {
                return ResourceManager.GetString("Error_InvalidIgnorableAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index value &apos;{0}&apos;..
        /// </summary>
        internal static string Error_InvalidIndex {
            get {
                return ResourceManager.GetString("Error_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location must be greater than the current location and less than the end of the source..
        /// </summary>
        internal static string Error_InvalidMoveLocation {
            get {
                return ResourceManager.GetString("Error_InvalidMoveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MustUnderstand condition failed on namespace &apos;{0}&apos;. Verify that you are not missing an assembly reference and that all assemblies have been built..
        /// </summary>
        internal static string Error_InvalidMustUnderstandAttribute {
            get {
                return ResourceManager.GetString("Error_InvalidMustUnderstandAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack URI &apos;{0}&apos; is not valid in this project..
        /// </summary>
        internal static string Error_InvalidPackURI {
            get {
                return ResourceManager.GetString("Error_InvalidPackURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project does not support &apos;{0}&apos; as the authority component of the pack URI..
        /// </summary>
        internal static string Error_InvalidPackURIAuthority {
            get {
                return ResourceManager.GetString("Error_InvalidPackURIAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ProcessContent attribute value. ProcessContent must contain a space delimited list of prefix qualified names or a &apos;[prefix]:*&apos; for all elements in the namespace. All prefixes referenced must also be declared ignorable in the same element that contains the ProcessContent attribute..
        /// </summary>
        internal static string Error_InvalidProcessContentAttribute {
            get {
                return ResourceManager.GetString("Error_InvalidProcessContentAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property path syntax..
        /// </summary>
        internal static string Error_InvalidPropertyPathSyntax {
            get {
                return ResourceManager.GetString("Error_InvalidPropertyPathSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than the previous location + length..
        /// </summary>
        internal static string Error_InvalidReadLocation {
            get {
                return ResourceManager.GetString("Error_InvalidReadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Requires syntax. Must be a space delimited list of prefixes..
        /// </summary>
        internal static string Error_InvalidRequiresSyntax {
            get {
                return ResourceManager.GetString("Error_InvalidRequiresSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is not part of the project or its &apos;Build Action&apos; property is not set to &apos;Resource&apos;..
        /// </summary>
        internal static string Error_InvalidResourceType {
            get {
                return ResourceManager.GetString("Error_InvalidResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because &apos;{0}&apos; is implemented in the same assembly, you must set the x:Name attribute rather than the {1} attribute..
        /// </summary>
        internal static string Error_InvalidRuntimeName {
            get {
                return ResourceManager.GetString("Error_InvalidRuntimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String length cannot be negative..
        /// </summary>
        internal static string Error_InvalidStringLength {
            get {
                return ResourceManager.GetString("Error_InvalidStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XAML TypeArgument syntax..
        /// </summary>
        internal static string Error_InvalidTypeArgumentSyntax {
            get {
                return ResourceManager.GetString("Error_InvalidTypeArgumentSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format for a type..
        /// </summary>
        internal static string Error_InvalidTypeFormat {
            get {
                return ResourceManager.GetString("Error_InvalidTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI must be an absolute URI and be of the correct format..
        /// </summary>
        internal static string Error_InvalidUri {
            get {
                return ResourceManager.GetString("Error_InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mapping URI syntax. Must take the form &apos;using:&lt;namespace&gt;&apos;..
        /// </summary>
        internal static string Error_InvalidUsingSyntax {
            get {
                return ResourceManager.GetString("Error_InvalidUsingSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; is not a valid XAML name..
        /// </summary>
        internal static string Error_InvalidXamlName {
            get {
                return ResourceManager.GetString("Error_InvalidXamlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is not part of the project or its &apos;Build Action&apos; property is not set to &apos;Resource&apos;..
        /// </summary>
        internal static string Error_InvalidXamlType {
            get {
                return ResourceManager.GetString("Error_InvalidXamlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML attribute &apos;{0}&apos; is not defined. Expected xml:space or xml:lang..
        /// </summary>
        internal static string Error_InvalidXmlAttribute {
            get {
                return ResourceManager.GetString("Error_InvalidXmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XmlnsDeclaration occurs in assembly &apos;{0}&apos;. XmlnsDeclaration references a namespace &apos;{1}&apos; that is not in the assembly..
        /// </summary>
        internal static string Error_InvalidXmlnsDefinitionAttribute {
            get {
                return ResourceManager.GetString("Error_InvalidXmlnsDefinitionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid xml:space value &apos;{0}&apos;. The xml:space value must be either &apos;default&apos; or &apos;preserve&apos;..
        /// </summary>
        internal static string Error_InvalidXmlSpace {
            get {
                return ResourceManager.GetString("Error_InvalidXmlSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member invocation is not supported for &apos;{0}.{1}&apos;..
        /// </summary>
        internal static string Error_InvocationNotSupported {
            get {
                return ResourceManager.GetString("Error_InvocationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key attribute can be used only on a tag contained in an IDictionary type property..
        /// </summary>
        internal static string Error_KeyOnlyAllowedInDictionary {
            get {
                return ResourceManager.GetString("Error_KeyOnlyAllowedInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A key is required for a dictionary entry..
        /// </summary>
        internal static string Error_KeyRequired {
            get {
                return ResourceManager.GetString("Error_KeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All objects added to an IDictionary must have a Key attribute or some other type of key associated with them..
        /// </summary>
        internal static string Error_KeyRequiredInDictionary {
            get {
                return ResourceManager.GetString("Error_KeyRequiredInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element cannot have both x:Load and x:DeferLoadStrategy..
        /// </summary>
        internal static string Error_LoadAndDeferLoad {
            get {
                return ResourceManager.GetString("Error_LoadAndDeferLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XAML document has exceeded the maximum supported depth..
        /// </summary>
        internal static string Error_MaxDepthReached {
            get {
                return ResourceManager.GetString("Error_MaxDepthReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not accessible..
        /// </summary>
        internal static string Error_MemberNotAccessible {
            get {
                return ResourceManager.GetString("Error_MemberNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; not found in type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_MemberNotFound {
            get {
                return ResourceManager.GetString("Error_MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method name &apos;{0}&apos; is not a valid language identifier..
        /// </summary>
        internal static string Error_MethodNameInvalid {
            get {
                return ResourceManager.GetString("Error_MethodNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected argument of type &apos;{0}&apos;, but found &apos;{1}&apos;..
        /// </summary>
        internal static string Error_MismatchedParameterType {
            get {
                return ResourceManager.GetString("Error_MismatchedParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An x:Class attribute is required to generate an event handler. Modify the root element of the XAML document to include an x:Class attribute to specify which class handles events for this XAML document and try again..
        /// </summary>
        internal static string Error_MissingBindingClass {
            get {
                return ResourceManager.GetString("Error_MissingBindingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity references or sequences beginning with an ampersand &apos;&amp;&apos; must be terminated with a semicolon &apos;;&apos;..
        /// </summary>
        internal static string Error_MissingSemicolonInEntity {
            get {
                return ResourceManager.GetString("Error_MissingSemicolonInEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; is required, but it could not be resolved..
        /// </summary>
        internal static string Error_MissingService {
            get {
                return ResourceManager.GetString("Error_MissingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A source changer cannot be modified after its Done method has been called..
        /// </summary>
        internal static string Error_ModifyDoneChanger {
            get {
                return ResourceManager.GetString("Error_ModifyDoneChanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Move method cannot be called without specifying a reader..
        /// </summary>
        internal static string Error_MoveWithoutReader {
            get {
                return ResourceManager.GetString("Error_MoveWithoutReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An AlternateContent element at the root can have only one element in the chosen Choice or Fallback element..
        /// </summary>
        internal static string Error_MultipleElementsInRootAlternateContent {
            get {
                return ResourceManager.GetString("Error_MultipleElementsInRootAlternateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a target ResourceDictionary..
        /// </summary>
        internal static string Error_MustSelectResourceDestination {
            get {
                return ResourceManager.GetString("Error_MustSelectResourceDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined CLR namespace. The &apos;clr-namespace&apos; URI refers to a namespace &apos;{0}&apos; that could not be found..
        /// </summary>
        internal static string Error_NamespaceNotFoundInAssembly {
            get {
                return ResourceManager.GetString("Error_NamespaceNotFoundInAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions cannot have other functions as parameters..
        /// </summary>
        internal static string Error_NestedBindFunction {
            get {
                return ResourceManager.GetString("Error_NestedBindFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly must be specified for XAML files that are not part of a project. Reopen this XAML file after adding it to a project, close this file and reopen it using the project it is associated with, or modify the clr-namespace to include the name of the assembly..
        /// </summary>
        internal static string Error_NoDefaultAssembly {
            get {
                return ResourceManager.GetString("Error_NoDefaultAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions are only supported at the end of the bind path..
        /// </summary>
        internal static string Error_NonLeafBindFunction {
            get {
                return ResourceManager.GetString("Error_NonLeafBindFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The named entity &apos;&amp;{0};&apos; is not defined in XAML..
        /// </summary>
        internal static string Error_NoSuchNamedEntity {
            get {
                return ResourceManager.GetString("Error_NoSuchNamedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The designer requires a markup text model in order to display.  The project you are currently using does not offer a text model..
        /// </summary>
        internal static string Error_NoTextModel {
            get {
                return ResourceManager.GetString("Error_NoTextModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not usable as an object element because it is not public or does not define a public parameterless constructor or a type converter..
        /// </summary>
        internal static string Error_ObjectIsNotConstructable {
            get {
                return ResourceManager.GetString("Error_ObjectIsNotConstructable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An AlternateContent element can contain only one Fallback element. .
        /// </summary>
        internal static string Error_OnlyOneFallbackAllowed {
            get {
                return ResourceManager.GetString("Error_OnlyOneFallbackAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-write access to a binary model is not currently supported..
        /// </summary>
        internal static string Error_OnlyReadAccessSupported {
            get {
                return ResourceManager.GetString("Error_OnlyReadAccessSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open document &apos;{0}&apos;..
        /// </summary>
        internal static string Error_OpenDocumentFailed {
            get {
                return ResourceManager.GetString("Error_OpenDocumentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The designer does not support an application URI in an assembly other than the application.  Change &apos;{0}&apos; to be relative to the XAML file or fully qualify it with &apos;{1}&apos;..
        /// </summary>
        internal static string Error_ProjectMustBeApplication {
            get {
                return ResourceManager.GetString("Error_ProjectMustBeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property elements cannot be in the middle of an element&apos;s content. They must be before or after the content..
        /// </summary>
        internal static string Error_PropertiesInMiddleOfContent {
            get {
                return ResourceManager.GetString("Error_PropertiesInMiddleOfContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is set more than once..
        /// </summary>
        internal static string Error_PropertyAlreadySet {
            get {
                return ResourceManager.GetString("Error_PropertyAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property element cannot be the direct content of another property element..
        /// </summary>
        internal static string Error_PropertyElementSyntaxNotLegalHere {
            get {
                return ResourceManager.GetString("Error_PropertyElementSyntaxNotLegalHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is not declared as an attachable property..
        /// </summary>
        internal static string Error_PropertyIsNotAttachable {
            get {
                return ResourceManager.GetString("Error_PropertyIsNotAttachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is not attachable to elements of type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_PropertyNotAttachableTo {
            get {
                return ResourceManager.GetString("Error_PropertyNotAttachableTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; does not support values of type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_PropertyTypeMismatch {
            get {
                return ResourceManager.GetString("Error_PropertyTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The design time assembly &apos;{0}&apos; you have compiled against is not the same version used by $(VSGeneralBrandName).  Recompile your design time assemblies using references from this version of $(VSGeneralBrandName)..
        /// </summary>
        internal static string Error_RecompileDesignAssembly {
            get {
                return ResourceManager.GetString("Error_RecompileDesignAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required $(VSGeneralBrandName) Service &apos;{0}&apos; not found..
        /// </summary>
        internal static string Error_RequiredVSServiceNotFound {
            get {
                return ResourceManager.GetString("Error_RequiredVSServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice element must contain a Requires attribute..
        /// </summary>
        internal static string Error_RequiresRequired {
            get {
                return ResourceManager.GetString("Error_RequiresRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource &apos;{0}&apos; could not be found. It should be located at &apos;{1}&apos; but the file is not present..
        /// </summary>
        internal static string Error_ResourceNotFound {
            get {
                return ResourceManager.GetString("Error_ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web response has been closed..
        /// </summary>
        internal static string Error_ResponseClosed {
            get {
                return ResourceManager.GetString("Error_ResponseClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function return type &apos;{0}&apos; must match binding target type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_ReturnTypeInvalid {
            get {
                return ResourceManager.GetString("Error_ReturnTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text not allowed as content in a dictionary or an array property..
        /// </summary>
        internal static string Error_StringNotAllowedInDictionary {
            get {
                return ResourceManager.GetString("Error_StringNotAllowedInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is used like a markup extension but does not derive from MarkupExtension..
        /// </summary>
        internal static string Error_TypeIsNotAMarkupExtensions {
            get {
                return ResourceManager.GetString("Error_TypeIsNotAMarkupExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument is not a MarshalByRefObject or derived type..
        /// </summary>
        internal static string Error_TypeNotMBRO {
            get {
                return ResourceManager.GetString("Error_TypeNotMBRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the metadata for assembly &apos;{0}&apos;. This assembly may have been downloaded from the web.  See https://go.microsoft.com/fwlink/?LinkId=179545.  The following error was encountered during load: {1}.
        /// </summary>
        internal static string Error_UnableToLoadAssemlby {
            get {
                return ResourceManager.GetString("Error_UnableToLoadAssemlby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachable property &apos;{0}&apos; was not found in type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_UndefinedAttachableProperty {
            get {
                return ResourceManager.GetString("Error_UndefinedAttachableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; was not found in type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_UndefinedProperty {
            get {
                return ResourceManager.GetString("Error_UndefinedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built..
        /// </summary>
        internal static string Error_UndefinedType {
            get {
                return ResourceManager.GetString("Error_UndefinedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The open angle bracket character &apos;&lt;&apos; is not valid in an attribute. It should be written as &apos;&amp;lt;&apos;..
        /// </summary>
        internal static string Error_UnescapedOpenTag {
            get {
                return ResourceManager.GetString("Error_UnescapedOpenTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; is not defined in the markup compatibility namespace..
        /// </summary>
        internal static string Error_UnexpectedAttribute {
            get {
                return ResourceManager.GetString("Error_UnexpectedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; not defined in the markup compatibility namespace..
        /// </summary>
        internal static string Error_UnexpectedElement {
            get {
                return ResourceManager.GetString("Error_UnexpectedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is not valid in an AlternateContent element..
        /// </summary>
        internal static string Error_UnexpectedText {
            get {
                return ResourceManager.GetString("Error_UnexpectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character sequence &apos;{0}&apos; was not expected at this location..
        /// </summary>
        internal static string Error_UnexpectedToken {
            get {
                return ResourceManager.GetString("Error_UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; from the XAML namespace is not defined..
        /// </summary>
        internal static string Error_UnknownXamlAttribute {
            get {
                return ResourceManager.GetString("Error_UnknownXamlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Refactor Qualified Name..
        /// </summary>
        internal static string Error_UnrecognizedRQName {
            get {
                return ResourceManager.GetString("Error_UnrecognizedRQName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project does not support paths relative to the root application directory. Remove the leading &apos;/&apos; qualifier from the &apos;{0}&apos; path to correct the problem..
        /// </summary>
        internal static string Error_UnsupportedRootRelativePath {
            get {
                return ResourceManager.GetString("Error_UnsupportedRootRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the CDATA block was not found. CDATA blocks are terminated with the characters &apos;]]&gt;&apos;..
        /// </summary>
        internal static string Error_UnterminatedCharacterData {
            get {
                return ResourceManager.GetString("Error_UnterminatedCharacterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the comment was not found. Comments are terminated with the characters &apos;--&gt;&apos;..
        /// </summary>
        internal static string Error_UnterminatedComment {
            get {
                return ResourceManager.GetString("Error_UnterminatedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the processing instruction was not found. Processing instructions are terminated with the characters &apos;?&gt;&apos;..
        /// </summary>
        internal static string Error_UnterminatedProcessingInstruction {
            get {
                return ResourceManager.GetString("Error_UnterminatedProcessingInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the string was not found. The string is terminated with a ({0}) character..
        /// </summary>
        internal static string Error_UnterminatedString {
            get {
                return ResourceManager.GetString("Error_UnterminatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the text block was not found. The character data must be included in an element..
        /// </summary>
        internal static string Error_UnterminatedXmlText {
            get {
                return ResourceManager.GetString("Error_UnterminatedXmlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined namespace. The &apos;using&apos; URI refers to a namespace &apos;{0}&apos; that could not be found..
        /// </summary>
        internal static string Error_UsingNamespaceNotFoundInAssembly {
            get {
                return ResourceManager.GetString("Error_UsingNamespaceNotFoundInAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the .NET Framework that is installed is not the correct version for this version of $(VSGeneralBrandName).  Some features of the XAML designer may not be available.  Repair $(VSGeneralBrandName) to correct this problem..
        /// </summary>
        internal static string Error_WrongFrameworkLoaded {
            get {
                return ResourceManager.GetString("Error_WrongFrameworkLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; from the XAML namespace is only accepted on the root element..
        /// </summary>
        internal static string Error_XamlAttributeOnlyValidOnRoot {
            get {
                return ResourceManager.GetString("Error_XamlAttributeOnlyValidOnRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An XData element in the XAML namespace can have only one child element..
        /// </summary>
        internal static string Error_XDataCanHaveOnlyOneElement {
            get {
                return ResourceManager.GetString("Error_XDataCanHaveOnlyOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic parameter is definition when expected to be reference {0}.
        /// </summary>
        internal static string GenericParameterDefinition {
            get {
                return ResourceManager.GetString("GenericParameterDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Called GetDeclarationName for a declaration node that can possibly contain multiple variable declarators..
        /// </summary>
        internal static string InvalidGetDeclarationNameMultipleDeclarators {
            get {
                return ResourceManager.GetString("InvalidGetDeclarationNameMultipleDeclarators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items: must be non-empty.
        /// </summary>
        internal static string ItemsMustBeNonEmpty {
            get {
                return ResourceManager.GetString("ItemsMustBeNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location must be provided in order to provide minimal type qualification..
        /// </summary>
        internal static string LocationMustBeProvided {
            get {
                return ResourceManager.GetString("LocationMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupOptions has an invalid combination of options.
        /// </summary>
        internal static string LookupOptionsHasInvalidCombo {
            get {
                return ResourceManager.GetString("LookupOptionsHasInvalidCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name conflict for name {0}.
        /// </summary>
        internal static string NameConflictForName {
            get {
                return ResourceManager.GetString("NameConflictForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchCriteria is expected..
        /// </summary>
        internal static string NoNoneSearchCriteria {
            get {
                return ResourceManager.GetString("NoNoneSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a C# symbol..
        /// </summary>
        internal static string NotACSharpSymbol {
            get {
                return ResourceManager.GetString("NotACSharpSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is not within syntax tree with full span {0}.
        /// </summary>
        internal static string PositionIsNotWithinSyntax {
            get {
                return ResourceManager.GetString("PositionIsNotWithinSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position must be within span of the syntax tree..
        /// </summary>
        internal static string PositionNotWithinTree {
            get {
                return ResourceManager.GetString("PositionNotWithinTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax node to be speculated cannot belong to a syntax tree from the current compilation..
        /// </summary>
        internal static string SpeculatedSyntaxNodeCannotBelongToCurrentCompilation {
            get {
                return ResourceManager.GetString("SpeculatedSyntaxNodeCannotBelongToCurrentCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission can have at most one syntax tree..
        /// </summary>
        internal static string SubmissionCanHaveAtMostOne {
            get {
                return ResourceManager.GetString("SubmissionCanHaveAtMostOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission can only include script code..
        /// </summary>
        internal static string SubmissionCanOnlyInclude {
            get {
                return ResourceManager.GetString("SubmissionCanOnlyInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax node is not within syntax tree.
        /// </summary>
        internal static string SyntaxNodeIsNotWithinSynt {
            get {
                return ResourceManager.GetString("SyntaxNodeIsNotWithinSynt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax tree already present.
        /// </summary>
        internal static string SyntaxTreeAlreadyPresent {
            get {
                return ResourceManager.GetString("SyntaxTreeAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyntaxTree &apos;{0}&apos; resulted from a #load directive and cannot be removed or replaced directly..
        /// </summary>
        internal static string SyntaxTreeFromLoadNoRemoveReplace {
            get {
                return ResourceManager.GetString("SyntaxTreeFromLoadNoRemoveReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax tree should be created from a submission..
        /// </summary>
        internal static string SyntaxTreeIsNotASubmission {
            get {
                return ResourceManager.GetString("SyntaxTreeIsNotASubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyntaxTree &apos;{0}&apos; not found to remove.
        /// </summary>
        internal static string SyntaxTreeNotFoundTo {
            get {
                return ResourceManager.GetString("SyntaxTreeNotFoundTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyntaxTreeSemanticModel must be provided in order to provide minimal type qualification..
        /// </summary>
        internal static string SyntaxTreeSemanticModelMust {
            get {
                return ResourceManager.GetString("SyntaxTreeSemanticModelMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method can only be used to create tokens - {0} is not a token kind..
        /// </summary>
        internal static string ThisMethodCanOnlyBeUsedToCreateTokens {
            get {
                return ResourceManager.GetString("ThisMethodCanOnlyBeUsedToCreateTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tree must have a root node with SyntaxKind.CompilationUnit.
        /// </summary>
        internal static string TreeMustHaveARootNodeWith {
            get {
                return ResourceManager.GetString("TreeMustHaveARootNodeWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tree not part of compilation.
        /// </summary>
        internal static string TreeNotPartOfCompilation {
            get {
                return ResourceManager.GetString("TreeNotPartOfCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type argument cannot be null.
        /// </summary>
        internal static string TypeArgumentCannotBeNull {
            get {
                return ResourceManager.GetString("TypeArgumentCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be &apos;var&apos;..
        /// </summary>
        internal static string TypeMustBeVar {
            get {
                return ResourceManager.GetString("TypeMustBeVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Microsoft.CodeAnalysis.CSharp.SyntaxFactory.Literal to create numeric literal tokens..
        /// </summary>
        internal static string UseLiteralForNumeric {
            get {
                return ResourceManager.GetString("UseLiteralForNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Microsoft.CodeAnalysis.CSharp.SyntaxFactory.Literal to create character literal tokens..
        /// </summary>
        internal static string UseLiteralForTokens {
            get {
                return ResourceManager.GetString("UseLiteralForTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Microsoft.CodeAnalysis.CSharp.SyntaxFactory.Identifier or Microsoft.CodeAnalysis.CSharp.SyntaxFactory.VerbatimIdentifier to create identifier tokens..
        /// </summary>
        internal static string UseVerbatimIdentifier {
            get {
                return ResourceManager.GetString("UseVerbatimIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number of type arguments.
        /// </summary>
        internal static string WrongNumberOfTypeArguments {
            get {
                return ResourceManager.GetString("WrongNumberOfTypeArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a {0} SemanticModel..
        /// </summary>
        internal static string WrongSemanticModelType {
            get {
                return ResourceManager.GetString("WrongSemanticModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The literal string &apos;]]&gt;&apos; is not allowed in element content..
        /// </summary>
        internal static string XML_CDataEndTagNotAllowed {
            get {
                return ResourceManager.GetString("XML_CDataEndTagNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate &apos;{0}&apos; attribute.
        /// </summary>
        internal static string XML_DuplicateAttribute {
            get {
                return ResourceManager.GetString("XML_DuplicateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End tag &apos;{0}&apos; does not match the start tag &apos;{1}&apos;..
        /// </summary>
        internal static string XML_ElementTypeMatch {
            get {
                return ResourceManager.GetString("XML_ElementTypeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an end tag for element &apos;{0}&apos;..
        /// </summary>
        internal static string XML_EndTagExpected {
            get {
                return ResourceManager.GetString("XML_EndTagExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End tag was not expected at this location..
        /// </summary>
        internal static string XML_EndTagNotExpected {
            get {
                return ResourceManager.GetString("XML_EndTagNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;&gt;&apos; or &apos;/&gt;&apos; to close tag &apos;{0}&apos;..
        /// </summary>
        internal static string XML_ExpectedEndOfTag {
            get {
                return ResourceManager.GetString("XML_ExpectedEndOfTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character at this location..
        /// </summary>
        internal static string XML_ExpectedEndOfXml {
            get {
                return ResourceManager.GetString("XML_ExpectedEndOfXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An identifier was expected..
        /// </summary>
        internal static string XML_ExpectedIdentifier {
            get {
                return ResourceManager.GetString("XML_ExpectedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect syntax was used in a comment..
        /// </summary>
        internal static string XML_IncorrectComment {
            get {
                return ResourceManager.GetString("XML_IncorrectComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid character was found inside an entity reference..
        /// </summary>
        internal static string XML_InvalidCharEntity {
            get {
                return ResourceManager.GetString("XML_InvalidCharEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character(s) &apos;{0}&apos; cannot be used at this location..
        /// </summary>
        internal static string XML_InvalidToken {
            get {
                return ResourceManager.GetString("XML_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unicode character..
        /// </summary>
        internal static string XML_InvalidUnicodeChar {
            get {
                return ResourceManager.GetString("XML_InvalidUnicodeChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitespace is not allowed at this location..
        /// </summary>
        internal static string XML_InvalidWhitespace {
            get {
                return ResourceManager.GetString("XML_InvalidWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character &apos;&lt;&apos; cannot be used in an attribute value..
        /// </summary>
        internal static string XML_LessThanInAttributeValue {
            get {
                return ResourceManager.GetString("XML_LessThanInAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing equals sign between attribute and attribute value..
        /// </summary>
        internal static string XML_MissingEqualsAttribute {
            get {
                return ResourceManager.GetString("XML_MissingEqualsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to undefined entity &apos;{0}&apos;..
        /// </summary>
        internal static string XML_RefUndefinedEntity_1 {
            get {
                return ResourceManager.GetString("XML_RefUndefinedEntity_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing closing quotation mark for string literal..
        /// </summary>
        internal static string XML_StringLiteralNoEndQuote {
            get {
                return ResourceManager.GetString("XML_StringLiteralNoEndQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-ASCII quotations marks may not be used around string literals..
        /// </summary>
        internal static string XML_StringLiteralNonAsciiQuote {
            get {
                return ResourceManager.GetString("XML_StringLiteralNonAsciiQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string literal was expected, but no opening quotation mark was found..
        /// </summary>
        internal static string XML_StringLiteralNoStartQuote {
            get {
                return ResourceManager.GetString("XML_StringLiteralNoStartQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required white space was missing..
        /// </summary>
        internal static string XML_WhitespaceMissing {
            get {
                return ResourceManager.GetString("XML_WhitespaceMissing", resourceCulture);
            }
        }
    }
}
